services:
  veriprop-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - veriprop-api

  veriprop-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
